apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      securityContext:
        runAsUser: 0  
      containers:
      - name: jenkins-agent
        image: yonatankaplounov/jenkinsslave:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: JENKINS_URL
          value: "http://jenkins-0.jenkins:8080/"       
        - name: JENKINS_AGENT_NAME
          value: "agent1"
        - name: JENKINS_SECRET
          value:  "jenkins"  
          
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      nodeSelector: {}
      tolerations: []
