apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      securityContext:
        runAsUser: 0  
      containers:
      - name: jenkins-agent
        image: docker:dind 
        imagePullPolicy: Always
        securityContext:
          privileged: true       
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        command: ["/bin/sh"]
        args: ["-c","sleep infinity"]
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      nodeSelector: {}
      tolerations: []
